name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *" # Run once a Day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    # Work flow runs on the latest unbuntu environment
    runs-on: ubuntu-latest

    steps:
      # Checkout LeetCode-Stats (source code + Display.svg update target)
      - name: Checkout LeetCode-StatsSync repository
        uses: actions/checkout@v4 # Clones a GitHub Repo
        with:
          repository: SailudevikaMatta/LeetCode-StatsSync # Repo to Clone
          path: LeetCode-StatsSync # Saves the cloned repo under the provided name
          token: ${{ secrets.PAT }}  # Token is used for Authentication instead of passwords

      #  Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5 # Set ups a clean python environment
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          cd LeetCode-StatsSync
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run script to update Display.svg and README.md
      - name: Run Update Script
        run: |
          cd LeetCode-StatsSync
          python app.py

      # Commit and push Display.svg to LeetCode-Stats
      - name: Commit Display.svg to LeetCode-Stats
        run: |
          cd LeetCode-StatsSync
          git config user.name "Devika Automation"
          git config user.email "devikamatta7@gmail.com"
          git add Display.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Display.svg"
          git push origin main
